# 0D tensor/scalar

In [2]:
import numpy as np

In [3]:
a=np.array(3)

In [4]:
a

array(3)

In [5]:
a.ndim

0

# 1D tensor/vector

In [8]:
a=np.array([1,2,3,4])

In [9]:
a

array([1, 2, 3, 4])

In [10]:
a.ndim

1

# 2D tensor/ Metrices

In [11]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])

In [12]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [13]:
a.ndim

2

# 3D tensor

In [14]:

a = np.array([[1, 2, 3],
              [3, 4, 5],
              [5, 6, 7]])


3D Tensor:
[[[1 2 3]
  [3 4 5]
  [5 6 7]]]
Shape of the 3D Tensor: (1, 3, 3)


In [15]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [16]:
a.ndim

2