In [1]:
# Importing libraries

import pandas as pd
import numpy as np


In [2]:
#  Import datasets
df= pd.read_csv("Data.csv")

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  45600.0       Yes
2  Germany  30.0  56000.0        No
3    Spain  33.0  61000.0        No
4  Germeny  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  71000.0        No
7   France  48.0  83000.0       Yes
8  Germeny  56.0  63000.0        No
9   France  37.0  67000.0       Yes

In [6]:
x=df[['Country','Age','Salary']].values   #independent variables

In [7]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 45600.0],
       ['Germany', 30.0, 56000.0],
       ['Spain', 33.0, 61000.0],
       ['Germeny', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 71000.0],
       ['France', 48.0, 83000.0],
       ['Germeny', 56.0, 63000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [12]:
y=df[['Purchased']].values #dependent variable  (with arrau values)

In [13]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [24]:
# Finding missing datas and handling missing values
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [27]:
imputer=imputer.fit(x[:,1:3])

In [29]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [30]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 45600.0],
       ['Germany', 30.0, 56000.0],
       ['Spain', 33.0, 61000.0],
       ['Germeny', 40.0, 64066.666666666664],
       ['France', 35.0, 58000.0],
       ['Spain', 38.888888888888886, 71000.0],
       ['France', 48.0, 83000.0],
       ['Germeny', 56.0, 63000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [31]:
# Encoding Categorical Datas

from sklearn.preprocessing import LabelEncoder

In [32]:
label_encoder=LabelEncoder()

In [34]:
x[:,0]=label_encoder.fit_transform(x[:,0])

In [35]:
x

array([[0, 44.0, 72000.0],
       [3, 27.0, 45600.0],
       [1, 30.0, 56000.0],
       [3, 33.0, 61000.0],
       [2, 40.0, 64066.666666666664],
       [0, 35.0, 58000.0],
       [3, 38.888888888888886, 71000.0],
       [0, 48.0, 83000.0],
       [2, 56.0, 63000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
onehotencoder=OneHotEncoder()

In [39]:
onehot_encoded = onehotencoder.fit_transform(df[['Country']])

In [40]:
onehot_encoded_array = onehot_encoded.toarray()

In [41]:
onehot_encoded_array

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [42]:
# for purchase

labelencoder_Y=LabelEncoder()

In [43]:
labelencoder_Y.fit_transform(y)

C:\Users\biraj\anaconda3\envs\venv\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [45]:
# Splitting dataset into training and testing set

from sklearn.model_selection import train_test_split 

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [52]:
x_train

array([[2, 40.0, 64066.666666666664],
       [0, 37.0, 67000.0],
       [3, 27.0, 45600.0],
       [3, 38.888888888888886, 71000.0],
       [0, 48.0, 83000.0],
       [3, 33.0, 61000.0],
       [0, 44.0, 72000.0],
       [0, 35.0, 58000.0]], dtype=object)

In [54]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

In [55]:
sc_x=StandardScaler()

In [57]:
x_train=sc_x.fit_transform(x_train)

In [58]:
x_test=sc_x.fit_transform(x_test)