In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
print(arr)
#using loop
for item in arr:
    print(item,end=' ')

[1 2 3 4 5]
1 2 3 4 5 

In [4]:
arr[0]

1

In [5]:
arr[1]

2

In [6]:
print(arr[2])

3


In [7]:
arr[-1]

5

In [8]:
arr[-2]

4

In [9]:
for index in range(len(arr)):
    print(arr[index])

1
2
3
4
5


In [10]:
#Creating Array with 5 zeros

k=np.zeros(5)
print(k)

[0. 0. 0. 0. 0.]


In [11]:
# Creating Array with 5 ones

l=np.ones(5)
print(l)

[1. 1. 1. 1. 1.]


# Sorting the Content of Arrays

In [12]:
original_arrays=np.array([10,35,20,45,55,40,30,16])

print("Original Arrays: ",original_arrays)

after_sorting=np.sort(original_arrays)

print("After Sorting Arrays: ", after_sorting)


Original Arrays:  [10 35 20 45 55 40 30 16]
After Sorting Arrays:  [10 16 20 30 35 40 45 55]


# Slicing in Numpy

In [13]:
import numpy as np
arr=np.array([1,3,4,5,6,7,7,8])
print(arr)

[1 3 4 5 6 7 7 8]


In [14]:
print(arr[2:5])

[4 5 6]


In [15]:
print(arr[2:6:3])

[4 7]


In [16]:
print(arr[:4])

[1 3 4 5]


In [17]:
print(arr[4:])

[6 7 7 8]


In [18]:
print(arr[-4:-1])

[6 7 7]


# Mathematical Operation in and array

In [19]:
print("Original Array:", arr)

Original Array: [1 3 4 5 6 7 7 8]


In [20]:
arr=arr+5
print("After additional operation: ",arr)

After additional operation:  [ 6  8  9 10 11 12 12 13]


In [21]:
arr=arr-3
print("After additional operation: ",arr)

After additional operation:  [ 3  5  6  7  8  9  9 10]


# Searching Arrays

In [22]:
import numpy as np
aray=np.array([1,3,4,5,6,7,7,8,9,11,0,10])
x=np.where(aray==8)
print(x)

(array([7], dtype=int64),)


# Filtering an array

In [23]:
import numpy as np
arr = np.array([2, 3, 4, 5, 6, 7])
x = np.array([True, False, True, False, True, False]) 
newArr = arr[x]
print(newArr)


[2 4 6]


# Check given array is empty or not

In [29]:
# arr=np.array([])
arr=np.array([1,2,3])

if (arr.size==0):
    print("Array is empty!")
else:
    print("Array is not empty.")
    print("Array contains: ",arr)


Array is not empty.
Array contains:  [1 2 3]


# Creating and displaying 2D array

In [32]:
import numpy as np

arr=np.array([[1,2],[3,4]])
print(arr)

for items in arr:
    print(items)

[[1 2]
 [3 4]]
[1 2]
[3 4]


In [33]:
# Check dimention of array

A=np.array([1,2,3,4])
B=np.array([[1,2,3],[3,4,5]])

print("Dimention of A: ", A.ndim)
print("Dimention of B: ", B.ndim)


Dimention of A:  1
Dimention of B:  2


In [36]:
# Size attribute
print("Size of  elements in A: ",A.size)
print("Size of  elements in B: ",B.size)


Size of  elements in A:  4
Size of  elements in B:  6


# Shaping and reshaping 

In [38]:
# Shape

import numpy as np

arr=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
print("Order is: ",arr.shape)

Order is:  (3, 4)


In [44]:
# 3*4
# 6*2
#4*3

# arr=arr.reshape(6,2)
arr=arr.reshape(4,3)
# print(arr)
for x in arr:
    print(x)

[1 2 3]
[4 2 3]
[4 5 3]
[4 5 6]


In [47]:
# Creating an identity matrix

id=np.eye(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
# arange()  function
# x=np.arange(1,10)
# x=np.arange(1,10,2)
x=np.arange(-1,1,0.1)
print(x)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


In [57]:
# linspace():
# Return evenly spaced numbers over a specified interval
y=np.linspace(1,10)
print(y)


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [60]:
# Random arrays
# [0,1]
import numpy as np

x=np.random.rand(5)
print(x)

[0.47833917 0.54962937 0.45733353 0.81404153 0.65489616]


In [62]:
import numpy as np
x=np.random.rand(3,4)
print(x)

[[0.34434393 0.8947337  0.53918797 0.49078382]
 [0.74464765 0.70318436 0.72252013 0.4600337 ]
 [0.50991923 0.87141089 0.96537625 0.33096149]]


In [66]:
# Generate random matrices in integer 
import numpy as np

x=np.random.randint(100,size=(3,5))
# print(x)
for vals in x:
    print(vals)

[14  9 83 35 19]
[68 30 59 30 75]
[75 37  6 40  8]


In [70]:
# Creating a diagonal matrix

x=np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [72]:
# Flatten matrix:
# Flatten is a simple method to transform a matrix
# into a one-dimentional array

import numpy as np

arr=np.array([[1,3,5],[2,5,7],[5,7,9]])
print("Original matrix; ", arr)
print("Flatten Array: ",arr.flatten())

Original matrix;  [[1 3 5]
 [2 5 7]
 [5 7 9]]
Flatten Array:  [1 3 5 2 5 7 5 7 9]


In [74]:
# Trace of given matrix

import numpy as np

arr=np.array([[1,3,5],[2,5,7],[5,7,9]])

print("Original matrix; ", arr)

# Compute trace of matring
print("Trace of given matrix: ",arr.trace())

print("Trace:", sum(arr.diagonal()))

Original matrix;  [[1 3 5]
 [2 5 7]
 [5 7 9]]
Trace of given matrix:  15
Trace 15


In [75]:
# Finding transpose of a matrix

import numpy as np

arr=np.array([[1,3,5],[2,5,7],[5,7,9]])

print("Original MatriX: ",arr)
print("Transpose of a matrix: ", arr.transpose())

Original MatriX:  [[1 3 5]
 [2 5 7]
 [5 7 9]]
Transpose of a matrix:  [[1 2 5]
 [3 5 7]
 [5 7 9]]


# Q.no.1 Write a NumPy program that creates a 3x3 matrix of random integers between 0 and 9 and prints the maximum and minimum values of the matrix.

In [2]:
import numpy as np

mat=np.random.randint(0,10,size=(3,3))
print(mat)

max_val = np.max(mat)
min_val = np.min(mat)

print(f"Maximum value: {max_val}")
print(f"Minimum value: {min_val}")

[[8 9 1]
 [0 6 1]
 [6 7 7]]
Maximum value: 9
Minimum value: 0


# 2. Write a NumPy function that accepts two 1-D arrays of equal length and returns a new array containing the product of the corresponding elements in the input arrays.

In [3]:
import numpy as np

def mul(arr1, arr2):
    if len(a1) != len(a2):
        raise ValueError("Arrays must have equal length")
    
    return np.array(a1) * np.array(a2)


a1 = np.array([1, 3, 5, 7, 9])
a2 = np.array([2, 4, 6, 8, 10])

new= mul(a1, a2)
print("multiple product:", new)


multiple product: [ 2 12 30 56 90]


# 3. Write a NumPy program that creates a 5x5 identity matrix and replaces the diagonal elements with random integers between 0 and 9.

In [5]:
import numpy as np
arr=np.eye(5)
arr

random_integers=np.random.randint(0, 10, size=5)

np.fill_diagonal(arr, random_integers)

print(arr)

[[9. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 7.]]
